
project_id = "zkypxeoihxjrmbwqkeyd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://zkypxeoihxjrmbwqkeyd.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_email_change_enabled = false
max_frequency = 300

[functions.create-payment-intent]
verify_jwt = true

[functions.confirm-payment]
verify_jwt = false
