project_id = "zkypxeoihxjrmbwqkeyd"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[studio]
enabled = true

[inbucket]
enabled = true
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = [
  "https://zkypxeoihxjrmbwqkeyd.supabase.co",
  "http://localhost:8080/update-password",
  "https://zkypxeoihxjrmbwqkeyd.supabase.co/update-password"
]
jwt_expiry = 1209600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.create-payment-intent]
verify_jwt = true

[functions.confirm-payment]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[auth.email.smtp]
host = "smtp.resend.com"
port = 587
user = "resend"
pass = "env(RESEND_API_KEY)"
admin_email = "noreply@resend.dev"

[auth.email.template.recovery]
subject = ""
content_path = ""
