
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkypxeoihxjrmbwqkeyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpreXB4ZW9paHhqcm1id3FrZXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzI0NTgsImV4cCI6MjA2MzQwODQ1OH0.5e-rQR9Q9H_69nhhB50C8DtzbYiBXel9LPr57s1UUpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Database types for our application
export type ProjectPack = Database['public']['Tables']['project_packs']['Row'];
export type Project = Database['public']['Tables']['projects']['Row'];
export type Document = Database['public']['Tables']['documents']['Row'];
export type Student = Database['public']['Tables']['students']['Row'];
export type Entrepreneur = Database['public']['Tables']['entrepreneurs']['Row'];
export type UserProfile = Database['public']['Tables']['users']['Row'];
export type Message = Database['public']['Tables']['messages']['Row'];
export type Task = Database['public']['Tables']['tasks']['Row'];
